version: "3.8"
services:
  staffDB:
    container_name: staff_container_db
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123
    ports:
      - "8020:3306"
    volumes:
      - ./staff-db:/var/lib/mysql
    
  studentDB:
    container_name: student_container_db
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123
    ports:
      - "8021:3306"
    volumes:
      - ./student-db:/var/lib/mysql
    
  professorDB:
    container_name: professor_container_db
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123
    ports:
      - "8022:3306"
    volumes:
      - ./professor-db:/var/lib/mysql
    
  courseDB:
    container_name: course_container_db
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123
    ports:
      - "8023:3306"
    volumes:
      - ./course-db:/var/lib/mysql
    
  absenceDB:
    container_name: absence_container_db
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123
    ports:
      - "8024:3306"
    volumes:
      - ./absence-db:/var/lib/mysql

  keycloakDB:
    container_name: keycloak_container_db
    image: postgres:alpine
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Admin123
    ports:
      - "8025:5432"
    volumes:
      - ./keycloak-db:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    networks:
      - keycloak_network

  keycloak:
    container_name: keycloak_container_server
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - "8100:8080"
    depends_on:
      keycloakDB:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST : keycloakDB
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: Admin123
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: Admin123
    command: ["start-dev"]
    networks:
      - keycloak_network

  zookeeper:
    container_name: zookeeper_absence_container
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka_absence_container
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Random-Data-Generator:1:1:compact,Absence-Data-Analytics-Stream:1:1:compact"
    depends_on:
      - zookeeper

  eureka:
    container_name: absence_discovery_container
    image: absence/eureka-server:0.1
    ports:
      - "8761:8761"

  gateway:
    container_name: absence_gateway_container
    image: absence/gateway-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - eureka

volumes:
  staffDB:
    driver: local
  studentDB:
    driver: local
  professorDB:
    driver: local
  courseDB:
    driver: local
  absenceDB:
    driver: local
  keycloakDB:
    driver: local

networks:
  keycloak_network:
    driver: bridge